# Generated by Django 4.2.1 on 2023-06-01 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Module',
            new_name='ModuleModel',
        ),
    ]
