# Generated by Django 4.2.1 on 2023-06-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0002_rename_module_modulemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursemodel',
            old_name='created',
            new_name='created_on',
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
