# Generated by Django 4.2.1 on 2023-06-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0003_rename_created_coursemodel_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
